ansible_become: true
ansible_become_user: root
ansible_ssh_user: heat-admin

containerized: true
openshift_use_dnsmasq: False
openshift_deployment_type: origin
openshift_release: v1.5
openshift_image_tag: v1.5.0
enable_excluders: False
