---

- name: test
  hosts: localhost
  tasks:
    - add_host: name={{item}} groups=nodes
      with_items: "{{groups['compute']}}"
    - add_host: name={{item}} groups=nodes,masters
      with_items: "{{groups['controller']}}"
    - add_host: name={{item}} groups=OSEv3
      with_items: "{{groups['overcloud']}}"

- hosts: OSEv3
  vars:
    ansible_become: true
    ansible_become_user: root
    ansible_ssh_user: heat-admin
    containerized: true
    openshift_use_dnsmasq: False
    openshift_deployment_type: origin
    openshift_release: v1.5
    openshift_image_tag: v1.5.0
    enable_excluders: False

- hosts: nodes
  vars:
    containerized: true
    openshift_schedulable: true
    openshift_excluder_on: false
    connect_to: "{{inventory_hostname}}"
    openshift_ip: "{{inventory_hostname}}"
    openshift_hostname: "{{inventory_hostname}}"
    openshift_public_ip: "{{inventory_hostname}}"
    openshift_public_hostname: "{{inventory_hostname}}"

- hosts: masters
  vars:
    containerized: true
    openshift_schedulable: true
    openshift_excluder_on: false
    connect_to: "{{inventory_hostname}}"
    openshift_ip: "{{inventory_hostname}}"
    openshift_hostname: "{{inventory_hostname}}"
    openshift_public_ip: "{{inventory_hostname}}"
    openshift_public_hostname: "{{inventory_hostname}}"

- include: openshift-ansible/playbooks/byo/config.yml
